### PR TITLE
East Asia reboot

### LINKED ISSUE #238: Compatibility with mod "East Asia Reboot"
See if compatibility with mod _East Asia Reboot_ / _[아시아추가](https://gall.dcinside.com/mgallery/board/view/?id=crusaderkings&no=149906)_ is feasible and how

While the page is in Korean, the mod is an interesting expansion of CK3 to allow for Eastern Asia and also has scenarios up to 1836

### PR DESCRIPTION
**Pull request by IohannesIohannium**
Resolves #238

### CODE REVIEW

**Review by Zemurin — APPROVED** [review]
Most here looks sensible, some items look suspicious (having protestant at eu4 start might cause issues), but none of this will apply to east asia without province mapping scheme?

Waiting on that?

**Comment by IohannesIohannium** [comment]
> Most here looks sensible, some items look suspicious (having protestant at eu4 start might cause issues), but none of this will apply to east asia without province mapping scheme?
> 
> Waiting on that?

Yes, I'm working on mapping. Also, that mod has an 1836 scenario, justifying the existance of Protestant and Reformed.

**Comment by IohannesIohannium** [comment]
Will update province mappings with new East Asian Reboot mod patch before making this mergeable

**Comment by IohannesIohannium** [comment]
Can be merged in; difference is some more secondary baronies in Korea

**Pull request merged**
